language: rust
os:
  - linux
  - osx
  - windows
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
cache: cargo
script:
  - cargo build --verbose
  - cargo run
notifications:
  email:
    on_success: never
